package io.yak.framework.workflow.engine.validation;

/**
 * Stable error codes returned by DAG validation.
 */
public enum DagValidationErrorCode {
    WORKFLOW_CODE_BLANK,
    NODE_NULL,
    NODE_CODE_BLANK,
    NODE_TYPE_MISSING,
    DUPLICATE_NODE_CODE,
    EDGE_NULL,
    EDGE_SOURCE_BLANK,
    EDGE_TARGET_BLANK,
    UNKNOWN_EDGE_SOURCE,
    UNKNOWN_EDGE_TARGET,
    SELF_LOOP,
    DUPLICATE_EDGE,
    START_NODE_MISSING,
    MULTIPLE_START_NODES,
    END_NODE_MISSING,
    START_NODE_HAS_INCOMING_EDGE,
    END_NODE_HAS_OUTGOING_EDGE,
    CYCLE_DETECTED,
    NODE_UNREACHABLE_FROM_START,
    NODE_CANNOT_REACH_END
}
