<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.weifuwan</groupId>
        <artifactId>yak-schedule-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>yak-schedule-plugin-all</artifactId>
    <name>Yak Schedule Plugin All</name>
    <description>聚合全部内置调度引擎插件</description>
    <dependencies>
        <dependency>
            <groupId>io.github.weifuwan</groupId>
            <artifactId>yak-schedule-plugin-quartz</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.weifuwan</groupId>
            <artifactId>yak-schedule-plugin-xxl-job</artifactId>
        </dependency>
    </dependencies>
</project>
