-- Yak Security MariaDB 10.6+ baseline. 关系完整性由 Service 事务维护，不创建物理外键。
CREATE TABLE yak_security_dept (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', dept_name VARCHAR(64) NOT NULL COMMENT '部门名称', parent_id BIGINT NOT NULL DEFAULT 0 COMMENT '父部门主键，0 表示根节点', leaf TINYINT(1) NOT NULL COMMENT '是否叶子节点：0 否，1 是', level INT NOT NULL COMMENT '部门层级', description VARCHAR(255) NULL COMMENT '部门描述', create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除', app_name VARCHAR(64) NOT NULL COMMENT '应用级数据隔离键', active_dept_name VARCHAR(64) GENERATED ALWAYS AS (IF(is_delete=0,dept_name,NULL)) STORED COMMENT '未删除部门唯一键', PRIMARY KEY(id), UNIQUE KEY uk_dept_app_name(app_name,active_dept_name), KEY idx_dept_app_parent(app_name,parent_id), KEY idx_dept_app_delete(app_name,is_delete)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='部门表';
CREATE TABLE yak_security_message (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', title VARCHAR(128) NOT NULL COMMENT '消息标题', content VARCHAR(1024) NULL COMMENT '消息内容', read_tag TINYINT(1) NOT NULL DEFAULT 0 COMMENT '阅读状态：0 未读，1 已读', oplog_id BIGINT NULL COMMENT '操作日志主键', user_id BIGINT NOT NULL COMMENT '接收用户主键', create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除', app_name VARCHAR(64) NOT NULL COMMENT '应用级数据隔离键', PRIMARY KEY(id), KEY idx_message_app_user(app_name,user_id,is_delete), KEY idx_message_app_oplog(app_name,oplog_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='消息表';
CREATE TABLE yak_security_oplog (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', operator_ip VARCHAR(45) NOT NULL COMMENT '操作者 IP 地址', operator VARCHAR(64) NULL COMMENT '操作者账号', operate_page VARCHAR(64) NOT NULL COMMENT '操作页面', operate_type VARCHAR(64) NOT NULL COMMENT '操作类型', target_type VARCHAR(64) NOT NULL COMMENT '对象类型', target VARCHAR(128) NOT NULL COMMENT '操作对象', operation_methods VARCHAR(64) NOT NULL COMMENT '操作方式', detail TEXT NULL COMMENT '日志详情', create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除', app_name VARCHAR(64) NOT NULL COMMENT '应用级数据隔离键', PRIMARY KEY(id), KEY idx_oplog_app_operator(app_name,operator), KEY idx_oplog_app_time(app_name,create_time), KEY idx_oplog_app_delete(app_name,is_delete)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志表';
CREATE TABLE yak_security_oplog_extra (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', info VARCHAR(128) NULL COMMENT '扩展信息', type TINYINT NOT NULL COMMENT '信息类型：1 操作页面，2 操作类型，3 对象类型', create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除', app_name VARCHAR(64) NOT NULL COMMENT '应用级数据隔离键', PRIMARY KEY(id), KEY idx_oplog_extra_app_type(app_name,type,is_delete)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='操作日志扩展信息表';
CREATE TABLE yak_security_permission (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', permission_code VARCHAR(128) NOT NULL COMMENT '权限编码', permission_name VARCHAR(128) NOT NULL COMMENT '权限名称', parent_id BIGINT NOT NULL DEFAULT 0 COMMENT '父权限主键，0 表示根节点', leaf TINYINT(1) NOT NULL COMMENT '是否叶子权限：0 否，1 是', level INT NOT NULL COMMENT '权限层级', description VARCHAR(255) NULL COMMENT '权限描述', create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除', app_name VARCHAR(64) NOT NULL COMMENT '应用级数据隔离键', active_permission_code VARCHAR(128) GENERATED ALWAYS AS (IF(is_delete=0,permission_code,NULL)) STORED COMMENT '未删除权限唯一键', PRIMARY KEY(id), UNIQUE KEY uk_permission_app_code(app_name,active_permission_code), KEY idx_permission_app_parent(app_name,parent_id), KEY idx_permission_app_delete(app_name,is_delete)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='权限表';
CREATE TABLE yak_security_project (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', project_code VARCHAR(128) NOT NULL COMMENT '项目编码', project_name VARCHAR(128) NOT NULL COMMENT '项目名称', description VARCHAR(512) NOT NULL DEFAULT '' COMMENT '项目描述', dept_id BIGINT NOT NULL COMMENT '所属部门主键', running TINYINT(1) NOT NULL DEFAULT 1 COMMENT '运行状态：0 停用，1 启用', create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除', app_name VARCHAR(64) NOT NULL COMMENT '应用级数据隔离键', active_project_code VARCHAR(128) GENERATED ALWAYS AS (IF(is_delete=0,project_code,NULL)) STORED COMMENT '未删除项目唯一键', PRIMARY KEY(id), UNIQUE KEY uk_project_app_code(app_name,active_project_code), KEY idx_project_app_dept(app_name,dept_id), KEY idx_project_app_delete(app_name,is_delete)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目表';
CREATE TABLE yak_security_resource_type (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', type_name VARCHAR(64) NOT NULL COMMENT '资源类型名称', create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除', app_name VARCHAR(64) NOT NULL COMMENT '应用级数据隔离键', active_type_name VARCHAR(64) GENERATED ALWAYS AS (IF(is_delete=0,type_name,NULL)) STORED COMMENT '未删除资源类型唯一键', PRIMARY KEY(id), UNIQUE KEY uk_resource_type_app_name(app_name,active_type_name), KEY idx_resource_type_app_delete(app_name,is_delete)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='资源类型表';
CREATE TABLE yak_security_role (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', role_code VARCHAR(128) NOT NULL COMMENT '角色编码', role_name VARCHAR(128) NOT NULL COMMENT '角色名称', description VARCHAR(255) NULL COMMENT '角色描述', last_reviser VARCHAR(64) NULL COMMENT '最后修改人', create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除', app_name VARCHAR(64) NOT NULL COMMENT '应用级数据隔离键', active_role_code VARCHAR(128) GENERATED ALWAYS AS (IF(is_delete=0,role_code,NULL)) STORED COMMENT '未删除角色唯一键', PRIMARY KEY(id), UNIQUE KEY uk_role_app_code(app_name,active_role_code), KEY idx_role_app_delete(app_name,is_delete)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色表';
CREATE TABLE yak_security_user (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', user_name VARCHAR(64) NOT NULL COMMENT '用户账号', pw VARCHAR(2048) NOT NULL COMMENT '单向哈希密码', salt VARCHAR(64) NOT NULL DEFAULT '' COMMENT '密码盐（兼容字段）', real_name VARCHAR(128) NOT NULL DEFAULT '' COMMENT '真实姓名', phone VARCHAR(32) NOT NULL DEFAULT '' COMMENT '手机号码', email VARCHAR(128) NOT NULL DEFAULT '' COMMENT '电子邮箱', dept_id BIGINT NULL COMMENT '所属部门主键', status INT NOT NULL DEFAULT 1 COMMENT '用户状态：1 正常，2 禁用', create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除', app_name VARCHAR(64) NOT NULL COMMENT '应用级数据隔离键', active_user_name VARCHAR(64) GENERATED ALWAYS AS (IF(is_delete=0,user_name,NULL)) STORED COMMENT '未删除用户唯一键', PRIMARY KEY(id), UNIQUE KEY uk_user_app_name(app_name,active_user_name), KEY idx_user_app_dept(app_name,dept_id), KEY idx_user_app_email(app_name,email), KEY idx_user_app_phone(app_name,phone), KEY idx_user_app_delete(app_name,is_delete)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';
CREATE TABLE yak_security_role_permission (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', role_id BIGINT NOT NULL COMMENT '角色主键', permission_id BIGINT NOT NULL COMMENT '权限主键', create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除', app_name VARCHAR(64) NOT NULL COMMENT '应用级数据隔离键', active_relation TINYINT GENERATED ALWAYS AS (IF(is_delete=0,0,NULL)) STORED COMMENT '未删除关系唯一键', PRIMARY KEY(id), UNIQUE KEY uk_role_permission_active(app_name,role_id,permission_id,active_relation), KEY idx_role_permission_permission(app_name,permission_id,is_delete), KEY idx_role_permission_role(app_name,role_id,is_delete)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='角色权限关系表';
CREATE TABLE yak_security_user_project (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', user_id BIGINT NOT NULL COMMENT '用户主键', project_id BIGINT NOT NULL COMMENT '项目主键', create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除', app_name VARCHAR(64) NOT NULL COMMENT '应用级数据隔离键', active_relation TINYINT GENERATED ALWAYS AS (IF(is_delete=0,0,NULL)) STORED COMMENT '未删除关系唯一键', PRIMARY KEY(id), UNIQUE KEY uk_user_project_active(app_name,user_id,project_id,active_relation), KEY idx_user_project_project(app_name,project_id,is_delete), KEY idx_user_project_user(app_name,user_id,is_delete)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户项目关系表';
CREATE TABLE yak_security_user_resource (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', user_id BIGINT NOT NULL COMMENT '用户主键', project_id BIGINT NOT NULL COMMENT '项目主键', resource_type_id BIGINT NOT NULL COMMENT '资源类型主键', resource_id BIGINT NOT NULL COMMENT '业务资源主键', control_level TINYINT NOT NULL COMMENT '管理级别：1 查看，2 管理', create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除', app_name VARCHAR(64) NOT NULL COMMENT '应用级数据隔离键', active_relation TINYINT GENERATED ALWAYS AS (IF(is_delete=0,0,NULL)) STORED COMMENT '未删除关系唯一键', PRIMARY KEY(id), UNIQUE KEY uk_user_resource_active(app_name,user_id,project_id,resource_type_id,resource_id,active_relation), KEY idx_user_resource_project(app_name,project_id,is_delete), KEY idx_user_resource_type(app_name,resource_type_id,is_delete), KEY idx_user_resource_resource(app_name,resource_id,is_delete), KEY idx_user_resource_user(app_name,user_id,is_delete)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户资源关系表';
CREATE TABLE yak_security_user_role (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', user_id BIGINT NOT NULL COMMENT '用户主键', role_id BIGINT NOT NULL COMMENT '角色主键', create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除', app_name VARCHAR(64) NOT NULL COMMENT '应用级数据隔离键', active_relation TINYINT GENERATED ALWAYS AS (IF(is_delete=0,0,NULL)) STORED COMMENT '未删除关系唯一键', PRIMARY KEY(id), UNIQUE KEY uk_user_role_active(app_name,user_id,role_id,active_relation), KEY idx_user_role_role(app_name,role_id,is_delete), KEY idx_user_role_user(app_name,user_id,is_delete)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户角色关系表';
CREATE TABLE yak_security_config (
 id BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键', value_group VARCHAR(100) NOT NULL DEFAULT '' COMMENT '配置分组', value_name VARCHAR(100) NOT NULL DEFAULT '' COMMENT '配置名称', value TEXT NULL COMMENT '配置值', edit INT NOT NULL DEFAULT 1 COMMENT '编辑策略：1 不可编辑，2 可编辑', status INT NOT NULL DEFAULT 1 COMMENT '配置状态：1 正常，2 禁用', memo VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '备注', operator VARCHAR(64) NULL COMMENT '操作者', create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间', update_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间', is_delete TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除：0 未删除，1 已删除', app_name VARCHAR(64) NOT NULL COMMENT '应用级数据隔离键', active_config_name VARCHAR(100) GENERATED ALWAYS AS (IF(is_delete=0,value_name,NULL)) STORED COMMENT '未删除配置唯一键', PRIMARY KEY(id), UNIQUE KEY uk_config_app_group_name(app_name,value_group,active_config_name), KEY idx_config_app_status(app_name,status,is_delete)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='安全配置表';
