CREATE TABLE IF NOT EXISTS yak_security_user (id BIGINT PRIMARY KEY AUTO_INCREMENT, username VARCHAR(128) NOT NULL UNIQUE, password VARCHAR(512) NOT NULL, enabled BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS yak_security_role (id BIGINT PRIMARY KEY AUTO_INCREMENT, code VARCHAR(128) NOT NULL UNIQUE, name VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS yak_security_permission (id BIGINT PRIMARY KEY AUTO_INCREMENT, code VARCHAR(255) NOT NULL UNIQUE, name VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS yak_security_user_role (user_id BIGINT NOT NULL, role_id BIGINT NOT NULL, PRIMARY KEY (user_id, role_id));
CREATE TABLE IF NOT EXISTS yak_security_role_permission (role_id BIGINT NOT NULL, permission_id BIGINT NOT NULL, PRIMARY KEY (role_id, permission_id));
CREATE TABLE IF NOT EXISTS yak_security_operation_log (id BIGINT PRIMARY KEY AUTO_INCREMENT, user_id BIGINT, username VARCHAR(128), operation VARCHAR(255) NOT NULL, method VARCHAR(512) NOT NULL, success BOOLEAN NOT NULL, detail VARCHAR(2000), created_at TIMESTAMP NOT NULL);
